appName: Crop Health
APP:
  Name: Crop Health
  Logo: app_logo.png
  Location: Sudan
Client:
  Name: FGM International
  Logo: fgm.png
  Location: Sudan
  DataPath: ./clients/FGM.geojson
Us:
  Name: AmunData
  Logo: amundata_logo.png
  Location: Sudan
Sentinel:
  InstanceId: ce7942da-a85c-4e51-a1e4-93891c02b01a    
  ClientId: b7d4c014-806b-4cd6-9bf9-fb44b65e11a3   
  ClientSecret: 5JsIcvJp0AX570yngRoRcxQhwtCWRrFe

StartDate : 2020-06-01
appSemanticVersion: 0.9.3
ClientName: FGM
